export const FETCH_REDDIT_LIST = 'FETCH_REDDIT_LIST';
export const RECEIVE_REDDIT_LIST = 'RECEIVE_REDDIT_LIST';




export const REDDIT_LOGIN = 'REDDIT_LOGIN';
export const REDDIT_LOGIN_SUCCESS = 'REDDIT_LOGIN_SUCCESS';
export const REDDIT_LOGIN_FAIL = 'REDDIT_LOGIN_FAIL';
export const REDDIT_LOGOUT = 'REDDIT_LOGOUT';